//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.1
//     from Assets/LilLycanLord/Scripts/Homebrewed/Non - Monobehaviour Scripts/Input Actions/Dialogue Controls/DialogueControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @DialogueControls: IInputActionCollection2, IDisposable
{public InputActionAsset asset { get; }public @DialogueControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""DialogueControls"",
    ""maps"": [
        {
            ""name"": ""Dialogue_Keyboard"",
            ""id"": ""529eaa2c-d8c4-4565-9b7e-83c8efeb65ac"",
            ""actions"": [
                {
                    ""name"": ""Confirm"",
                    ""type"": ""PassThrough"",
                    ""id"": ""0863eb83-780b-427f-8dc2-aad9cc20d106"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skip"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b4466a5b-9a47-4d21-b689-b1cdef3780f3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a5536c24-bf33-4ccb-9c44-23e55d78e497"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c17a2818-92d9-41d4-ad1f-b712b6d3b47b"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Dialogue_Keyboard
        m_Dialogue_Keyboard = asset.FindActionMap("Dialogue_Keyboard", throwIfNotFound: true);
        m_Dialogue_Keyboard_Confirm = m_Dialogue_Keyboard.FindAction("Confirm", throwIfNotFound: true);
        m_Dialogue_Keyboard_Skip = m_Dialogue_Keyboard.FindAction("Skip", throwIfNotFound: true);
    }

    ~@DialogueControls()
    {
        UnityEngine.Debug.Assert(!m_Dialogue_Keyboard.enabled, "This will cause a leak and performance issues, DialogueControls.Dialogue_Keyboard.Disable() has not been called.");
    }public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Dialogue_Keyboard
    private readonly InputActionMap m_Dialogue_Keyboard;
    private List<IDialogue_KeyboardActions> m_Dialogue_KeyboardActionsCallbackInterfaces = new List<IDialogue_KeyboardActions>();
    private readonly InputAction m_Dialogue_Keyboard_Confirm;
    private readonly InputAction m_Dialogue_Keyboard_Skip;public struct Dialogue_KeyboardActions
    {
        private @DialogueControls m_Wrapper;public Dialogue_KeyboardActions(@DialogueControls wrapper) { m_Wrapper = wrapper; }public InputAction @Confirm => m_Wrapper.m_Dialogue_Keyboard_Confirm;public InputAction @Skip => m_Wrapper.m_Dialogue_Keyboard_Skip;public InputActionMap Get() { return m_Wrapper.m_Dialogue_Keyboard; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;public static implicit operator InputActionMap(Dialogue_KeyboardActions set) { return set.Get(); }/// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="Dialogue_KeyboardActions" />
        public void AddCallbacks(IDialogue_KeyboardActions instance)
        {
            if (instance == null || m_Wrapper.m_Dialogue_KeyboardActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Dialogue_KeyboardActionsCallbackInterfaces.Add(instance);
            @Confirm.started += instance.OnConfirm;
            @Confirm.performed += instance.OnConfirm;
            @Confirm.canceled += instance.OnConfirm;
            @Skip.started += instance.OnSkip;
            @Skip.performed += instance.OnSkip;
            @Skip.canceled += instance.OnSkip;
        }/// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="Dialogue_KeyboardActions" />
        private void UnregisterCallbacks(IDialogue_KeyboardActions instance)
        {
            @Confirm.started -= instance.OnConfirm;
            @Confirm.performed -= instance.OnConfirm;
            @Confirm.canceled -= instance.OnConfirm;
            @Skip.started -= instance.OnSkip;
            @Skip.performed -= instance.OnSkip;
            @Skip.canceled -= instance.OnSkip;
        }/// <seealso cref="Dialogue_KeyboardActions.UnregisterCallbacks(IDialogue_KeyboardActions)" />
        public void RemoveCallbacks(IDialogue_KeyboardActions instance)
        {
            if (m_Wrapper.m_Dialogue_KeyboardActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }/// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="Dialogue_KeyboardActions.AddCallbacks(IDialogue_KeyboardActions)" />
        /// <seealso cref="Dialogue_KeyboardActions.RemoveCallbacks(IDialogue_KeyboardActions)" />
        /// <seealso cref="Dialogue_KeyboardActions.UnregisterCallbacks(IDialogue_KeyboardActions)" />
        public void SetCallbacks(IDialogue_KeyboardActions instance)
        {
            foreach (var item in m_Wrapper.m_Dialogue_KeyboardActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Dialogue_KeyboardActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }public Dialogue_KeyboardActions @Dialogue_Keyboard => new Dialogue_KeyboardActions(this);/// <seealso cref="Dialogue_KeyboardActions.AddCallbacks(IDialogue_KeyboardActions)" />
    /// <seealso cref="Dialogue_KeyboardActions.RemoveCallbacks(IDialogue_KeyboardActions)" />
    public interface IDialogue_KeyboardActions
    {/// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnConfirm(InputAction.CallbackContext context);/// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSkip(InputAction.CallbackContext context);
    }
}
